version: '3.8'

services:
  bloggingplatform-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "8001:1433"

  bloggingplatform-app:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - bloggingplatform-db